# *************************************************************************
# **  Copyright (c) 2022 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Prepare next development version

# This workflow is triggered whenever there is a push on master (which only happens when merging because the branch is protected)

on: 
  push:
    branches:
      - master
      - prepare-next-dev # TEMPORARLY FOR TESTING

jobs:
  call-prepare-next-dev-workflow:
    name: Prepare next development version
    uses: riseclipse/riseclipse-developer/.github/workflows/Shared-prepare-next-dev.yml@prepare-next-dev # REF TO BE CHANGED
    with:
      jarPath1: riseclipse-validator-scl2003/fr.centralesupelec.edf.riseclipse.iec61850.scl.validator/target/RiseClipseValidatorSCL.jar
      jarPath2: riseclipse-validator-scl2003/fr.centralesupelec.edf.riseclipse.iec61850.scl.validator.ui/target/RiseClipseValidatorSCLApplication.jar
