# *************************************************************************
# **  Copyright (c) 2023-24 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release on DockerHub

# This CD workflow builds and push a docker image of the RiseClipse Validator SCL CLI tool
# with a specific tag for this git branch

on: workflow_dispatch

jobs:
  call-release-dockerhub-workflow:
    name: Release on DockerHub
    uses: riseclipse/riseclipse-developer/.github/workflows/Shared-Release-On-DockerHub.yml@master
    with:
      # tag is specific to this branch, but also related to the version of the validator
      # (see https://github.com/riseclipse/riseclipse-validator-scl2003/pull/122)
      release_version: ec61850-6-3-v1.2.7
      docker_repository: riseclipse-validator-scl
      release_latest: false
    secrets:
      DOCKER_USER: ${{ secrets.RISECLIPSE_DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.RISECLIPSE_DOCKER_ACCESS_TOKEN }}
