# *************************************************************************
# **  Copyright (c) 2023-2026 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release on DockerHub

# This CD workflow builds and push a docker image of the RiseClipse Validator SCL CLI tool
# with a specific version

on:
    workflow_dispatch

env:
    RELEASE_VERSION: 1.3.0-SNAPSHOT
    DOCKER_REPOSITORY: riseclipse-validator-scl
    DOCKER_PRE_TAG: ec61850-6-3-v

jobs:
  release-dockerhub-workflow:
    # Use a specific version to avoid unattended changes with latest
    runs-on: ubuntu-24.04

    steps: 
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.RISECLIPSE_DOCKER_USERNAME }}
        password: ${{ secrets.RISECLIPSE_DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image with given tag
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        build-args: RELEASE_VERSION=${{ env.RELEASE_VERSION }}
        tags: riseclipse/${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_PRE_TAG }}${{ env.RELEASE_VERSION }}
