# *************************************************************************
# **  Copyright (c) 2022-23 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# **
# **  This file is part of the RiseClipse tool
# **
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Build

# This workflow is triggered on every push to verify that the project builds correctly and runs Sonar + Unit tests

on: push

jobs:
  call-verify-workflow:
    name: Verify Project
    uses: riseclipse/riseclipse-developer/.github/workflows/Shared-Verify-Tools.yml@master
    with:
      jar_path_1: riseclipse-validator-scl2003/fr.centralesupelec.edf.riseclipse.iec61850.scl.validator/target/RiseClipseValidatorSCL.jar
      jar_path_2: riseclipse-validator-scl2003/fr.centralesupelec.edf.riseclipse.iec61850.scl.validator.ui/target/RiseClipseValidatorSCLApplication.jar
    secrets:
      SONAR_TOKEN: ${{ secrets.RISECLIPSE_SONAR_TOKEN }}

  snapshot-tests:
    name: SCL Validator Snapshot Tests
    runs-on: ubuntu-latest
    needs: call-verify-workflow

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download SCL validator jar
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.call-verify-workflow.outputs.artifact_1_name }}
          path: scl-validator

      - name: Checkout riseclipse-validator-scl2003-test
        uses: actions/checkout@v4
        with:
          repository: riseclipse/riseclipse-validator-scl2003-test
          path: riseclipse-validator-scl2003-test

      - name: Run SCL validator snapshot tests
        run: |
          cd riseclipse-validator-scl2003-test
          python run_tests.py --jar-path ${{ github.workspace }}/scl-validator/${{ needs.call-verify-workflow.outputs.artifact_1_name }}
